# Generated by Django 3.2.6 on 2021-08-18 21:20

import apps.books.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(default='English', max_length=50, verbose_name='language')),
                ('publication_date', models.DateField(null=True, verbose_name='publication date')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnails')),
                ('isbn', models.CharField(max_length=20, validators=[apps.books.validators.isbn_validator], verbose_name='isbn number')),
                ('amount_of_pages', models.IntegerField(verbose_name='amount of pages')),
                ('authors', models.ManyToManyField(related_name='books', to='authors.Author', verbose_name='authors')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
