# Generated by Django 3.2.6 on 2021-08-18 16:10

import apps.books.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(default='Polish', max_length=50)),
                ('publication_date', models.DateField(null=True)),
                ('title', models.CharField(max_length=200)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.FileField(null=True, upload_to='thumbnails')),
                ('isbn', models.CharField(max_length=20, validators=[apps.books.validators.isbn_validator])),
                ('amount_of_pages', models.IntegerField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='authors.author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
